### ISSUE TITLE
Application exemple "CodeDArmor" à mettre à jour ?

### ISSUE THREAD

**Issue by ApprentiCobaltian** [cobaltians/CodeDArmor#1]
Bonjour,

J'ai tenté de mettre en place l'application exemple "CodeDarmor" sous Android (https://github.com/cobaltians/CodeDArmor/tree/master/Android) mais je rencontre des erreurs lors de l'importation. Je pense que c'est des problèmes dû au changement de version comme dans un autre topic du forum (https://github.com/cobaltians/cobalt/issues/26).

Pour régler le problème j'ai : 
- modifier le fichier AndroidManifest.xml (numéro de la version SDK ciblée pour 21, la valeur de "android.name" de l'application pour mettre le nom entier du package),
- les fichiers "styles.xml" des dossiers "values-11" et "values-14" du dossier "res" (la valeur de "parent" modifier pour recopier les valeurs écrites dans l'application "Hello world").

Après ces modifications, il n'y a plus d'erreurs et l'appli se charge bien sur un smartphone mais elle ne semble pas fonctionner correctement...

J'aimerai pouvoir m'inspirer de cette application exemple pour comprendre Cobalt donc si vous pouvez me dire si c'est normal de ne pouvoir accéder qu'au menu de l'appli, cela m'aiderait grandement.

Merci d'avance pour votre aide,

JB

**Comment by cobaltians** [comment]
Bonjour JB,

Je crois que cette application ne fonctionne pas. Elle n'a en fait jamais été finie. :(

Utilise plutôt les samples qui sont dans les sources de Cobalt : Le "Catalog" ou le "HelloWorld" disponibles ici :

https://github.com/cobaltians/cobalt/tree/master/samples

J'ajoute un disclaimer sur la page d'accueil du repository "CodeDarmor" afin que d'autres ne soient pas tentés.

Guillaume

**Comment by ApprentiCobaltian** [comment]
Je vais regarde le "Catalog" dans ce cas, en plus il doit comporter plus de fonctionnalités.

Merci Guillaume !

JB
